### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Benny-** [Benny-/apng2webp#3]
Culprit: sh package does not work on windows
Solution: rewrite the code so it no longer depend on the sh package. This might not be too much work as I only used sh because I liked - syntactic - sugar.

**Comment by dreampiggy** [comment]
#5 

I added the Windows support, it use MinGW to build native libraries and runs well during my tests( Windows 10 x64). All the outputed animated WebP I tested contains the same MD5 Hash and look corretly.

MinGW GCC is a little different from Linux GCC, and old version APNG Optimizer 1.2 run buggy so I upadte it to the latest 1.4 version. The APNG Disassembler 2.6 runs well and no need to update. Also I found that is hard to modify from the latest version, so I leave it to you :D

A nother modify is the python script. It now use pbs for Windows subprocess and entry_points to support CLI, to make it cross-platform.

**Comment by Benny-** [comment]
Thank you for your contribution! It is now merged and a release will soon follow. I can't test this on windows at the moment. If anyone has any problems please make another issue.
