### ISSUE TITLE
Dependency license issue

### ISSUE THREAD

**Issue by dreampiggy** [Benny-/apng2webp#7]
The original APNG Optimizier [1.2](https://sourceforge.net/projects/apng/files/APNG_Optimizer/1.2/) license is zlib license. But I found that the old version modified apng2webp_apngopt license is LGPL license. I don't know whether these two license is compatible or not. So the 1.4 version I just leave it as LGPL. But maybe we should change back it to original zlib license ?

Additionaly, the original APNG Disassembler 2.6 license is zlib license. And the modified apngdisraw license is also zlib license. So why are these two dependency's license is different ?

@Benny-

**Comment by Benny-** [comment]
I will investigate this issue.

**Comment by Benny-** [comment]
The original apngopt author released it (version 1.0) as LGPL but later released versions use zlib. apng2webp_apngopt is based on the latest version and so it should be clearly indicated zlib license is used. I will make a commit soonish.
