### ISSUE TITLE
Continuous Integration such as travis-ci need ?

### ISSUE THREAD

**Issue by dreampiggy** [Benny-/apng2webp#8]
CI(Continuous Integration) can provide extra check for each commit. Do we need an CI such as travis-ci to build.

I think it's good when you do something refactoring. Write some simple test to make sure each commit works without manural test. For example, we could safely update the dependency and source code changes and create an pull request. If the build can not pass, the PR should be rejected. And this image convertor is good to test(use a set of APNG images and generate animated WebP)

Also we can provide automatically build release（such as auto upload binary build result to GitHub release page）through travis-ci. For Windows binary, because travis-ci does not support, just manural build and upload it.

I support travis-ci for my fork repo and maybe you can have have a try.

repo page: https://github.com/dreampiggy/apng2webp/tree/travis-ci
travis-ci page: https://travis-ci.org/dreampiggy/apng2webp

**Comment by Benny-** [comment]
This is a very good thing to have. Is http://littlesvr.ca/ your server? I think it is best to put all test images into the repo.

**Comment by dreampiggy** [comment]
@Benny- No, but I use those images to test.. If you prefer, we can create a test folder and save some test APNG images, then write an  script to test them to convert to WebP. I think it can provide the issue such ad my previous mistake that do not forbid dispose previous method of APNG Optimizier.

**Comment by Benny-** [comment]
Adding a [python setup.py test-suite](https://stackoverflow.com/questions/20941880/how-to-run-test-suite-in-python-setup-py) is also on my list now that we have a configuration for travis.

And let travis call this test suite.

**Comment by Benny-** [comment]
Okay. So the test suite will fetch the images from a server. I am okay with this. Can you place all my [test images](https://bennyjacobs.nl/tmp/apng2webp/examples/) on your server too?

**Comment by Benny-** [comment]
I was confused. That was not your server and you are okay with putting the images into the repo. Is this correct?

**Comment by Benny-** [comment]
I have yet to read https://docs.travis-ci.com/user/getting-started/ on how to setup travis properly. A pull request is not sufficient.

**Comment by dreampiggy** [comment]
Yeah, it's not my server, I just use those images to test. A better solution is to save a set of test images to git repo(because download each time ci build is time consuming), write test script and run test from travis-ci. The images set can from your server or wherever. If you'd like this, I can try soon.

**Comment by Benny-** [comment]
I concur. Having the images in the repo is best. As the lifetime of those test images will be linked with the project instead of some server which depends on DNS/Owner/Hoster/Network. I will accept any pull request related to making travis/testing work like this.

**Comment by dreampiggy** [comment]
#10 PR is here, seems CI works well (see that green passed check).
A clean CI build need 1 minute for both macOS and Linux (really fast). You can add more unit test for single python method or the other cli arg format, such as `apng2webp -loop 10 -bgcolor 255,255,255,255 input.png output.png`)

**Comment by Benny-** [comment]
Thank you for your contributions.
